name: $(Version).$(rev:r)
variables:
- template: variables/build.yaml 

trigger:
  branches:
    include:
    - '*'
stages:

- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: ${{ variables.vmImage }}
    steps:


    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: ${{ variables.ConnectedServiceName }}
        subscriptionName: ${{ variables.subscriptionName }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.RGName }}
        location: ${{ variables.location }}
        templateLocation: 'Linked artifact'
        csmFile: 'Blobstorage/template.json'
        csmParametersFile: 'Blobstorage/parameters.json'
        deploymentMode: 'Validation'