name: $(Version).$(rev:r)
variables:
- template: variables/build.yaml 

trigger:
  branches:
    include:
    - '*'
stages:

- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: ${{ variables.vmImage }}
    steps:

    - task: AzureResourceGroupDeployment@2
      inputs:
        ConnectedServiceName: ${{ variables.ConnectedServiceName }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.RGName }}
        location: ${{ variables.location }}
        csmFile: 'Blobstorage/template.json'
        csmParametersFile: 'Blobstorage/parameters.json'
        deploymentMode: 'Validation'
