# File: component-x-pipeline.yml
variables:
- template: variables/build.yml@template  # Template reference
pool:
  vmImage: ${{ variables.vmImage }}
steps:
- script: build x ${{ variables.arch }} ${{ variables.config }}