name: $(Version).$(rev:r)
variables:
- template: variables/build.yaml 

trigger:
  branches:
    include:
    - '*'
stages:

- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: ${{ variables.vmImage }}
    steps:


    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: 'ARMPipelineConnection'
        subscriptionName: 'ed2868f7-245f-46ad-ab89-b89340fbd4d7'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'JeganRG'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: 'Blobstorage/template.json'
        csmParametersFile: 'Blobstorage/parameters.json'
        deploymentMode: 'Validation'